// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419141337_AddDiscount")]
    partial class AddDiscount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Components"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Office Equipment"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mobile Devices"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cameras"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("BackendApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A standard mechanical keyboard for everyday use.",
                            ImagePath = "/images/products/keyboard.jpg",
                            IsPublished = true,
                            Name = "Keyboard",
                            Price = 49.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Ergonomic mouse with adjustable DPI.",
                            ImagePath = "/images/products/mouse.jpg",
                            IsPublished = true,
                            Name = "Mouse",
                            Price = 19.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "24-inch Full HD monitor with vibrant colors.",
                            ImagePath = "/images/products/monitor24.jpg",
                            IsPublished = true,
                            Name = "Monitor 24\"",
                            Price = 129.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "27-inch monitor ideal for gaming and productivity.",
                            ImagePath = "/images/products/monitor27.jpg",
                            IsPublished = true,
                            Name = "Monitor 27\"",
                            Price = 179.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 8,
                            Description = "Durable USB cable for charging and data transfer.",
                            ImagePath = "/images/products/usbCable.jpg",
                            IsPublished = true,
                            Name = "USB Cable",
                            Price = 9.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            Description = "High-speed HDMI cable for HD video and audio.",
                            ImagePath = "/images/products/hdmi.jpg",
                            IsPublished = true,
                            Name = "HDMI Cable",
                            Price = 14.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            Description = "Adjustable laptop stand for ergonomic setup.",
                            ImagePath = "/images/products/laptopStand.jpg",
                            IsPublished = true,
                            Name = "Laptop Stand",
                            Price = 29.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "HD webcam perfect for video calls and streaming.",
                            ImagePath = "/images/products/webcam.jpg",
                            IsPublished = true,
                            Name = "Webcam",
                            Price = 59.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Over-ear headphones with clear sound quality.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Headphones",
                            Price = 89.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Compact speakers with powerful sound.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Speakers",
                            Price = 49.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "USB microphone suitable for podcasting and streaming.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Microphone",
                            Price = 69.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            Description = "Smooth mouse pad for precise control.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Mouse Pad",
                            Price = 12.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Reliable 1TB external hard drive.",
                            ImagePath = "/images/products/externalDrive.jpg",
                            IsPublished = true,
                            Name = "External Hard Drive 1TB",
                            Price = 79.99m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "High-capacity 2TB external hard drive.",
                            ImagePath = "/images/products/externalDrive.jpg",
                            IsPublished = true,
                            Name = "External Hard Drive 2TB",
                            Price = 119.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Fast 500GB SSD for quick storage access.",
                            ImagePath = "/images/products/externalDrive.jpg",
                            IsPublished = true,
                            Name = "SSD 500GB",
                            Price = 69.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "1TB SSD with excellent read/write speeds.",
                            ImagePath = "/images/products/externalDrive.jpg",
                            IsPublished = true,
                            Name = "SSD 1TB",
                            Price = 119.99m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Portable 13-inch laptop for everyday tasks.",
                            ImagePath = "/images/products/pc.jpg",
                            IsPublished = true,
                            Name = "Laptop 13\"",
                            Price = 999.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Powerful 15-inch laptop for work and gaming.",
                            ImagePath = "/images/products/pc.jpg",
                            IsPublished = true,
                            Name = "Laptop 15\"",
                            Price = 1299.99m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "High-performance graphics card for gaming.",
                            ImagePath = "/images/products/graphicCard.jpg",
                            IsPublished = true,
                            Name = "Graphics Card",
                            Price = 399.99m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Motherboard compatible with latest CPUs.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Motherboard",
                            Price = 179.99m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Intel i5 processor suitable for most tasks.",
                            ImagePath = "/images/products/cpu.jpg",
                            IsPublished = true,
                            Name = "CPU i5",
                            Price = 249.99m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "High-end Intel i7 processor for performance.",
                            ImagePath = "/images/products/cpu.jpg",
                            IsPublished = true,
                            Name = "CPU i7",
                            Price = 349.99m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "8GB RAM module for everyday computing.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "RAM 8GB",
                            Price = 49.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "16GB RAM module for multitasking.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "RAM 16GB",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Reliable 500W power supply unit.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Power Supply 500W",
                            Price = 59.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "750W PSU for high-performance systems.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Power Supply 750W",
                            Price = 79.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Description = "Durable PC case with airflow design.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Case",
                            Price = 69.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Description = "Cooling fan to keep your PC temperature down.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Cooling Fan",
                            Price = 19.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Description = "Ergonomic gaming chair for comfort.",
                            ImagePath = "/images/products/chair.jpg",
                            IsPublished = true,
                            Name = "Gaming Chair",
                            Price = 199.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Description = "LED desk lamp with adjustable brightness.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Desk Lamp",
                            Price = 29.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Description = "Wi-Fi router for fast home networking.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Router",
                            Price = 79.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Description = "Network switch to expand your LAN.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Switch",
                            Price = 129.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Description = "Ethernet cable for stable connections.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Network Cable",
                            Price = 12.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            Description = "All-in-one printer for home or office.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Printer",
                            Price = 149.99m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            Description = "High-resolution document scanner.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Scanner",
                            Price = 89.99m,
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            Description = "Protective laptop bag with compartments.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Laptop Bag",
                            Price = 39.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 7,
                            Description = "10-inch tablet for media and light work.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Tablet 10\"",
                            Price = 299.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 7,
                            Description = "12-inch tablet for productivity and media.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Tablet 12\"",
                            Price = 399.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            Description = "Latest smartphone with high-resolution camera.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            Description = "Smartwatch with health tracking features.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Smartwatch",
                            Price = 199.99m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 8,
                            Description = "Protective phone case with stylish design.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Phone Case",
                            Price = 19.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 8,
                            Description = "Screen protector to prevent scratches.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Screen Protector",
                            Price = 14.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            Description = "High-capacity portable charger.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Portable Charger",
                            Price = 29.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 8,
                            Description = "Portable Bluetooth speaker with good sound.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Bluetooth Speaker",
                            Price = 49.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            Description = "USB hub to expand your connectivity.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "USB Hub",
                            Price = 24.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 8,
                            Description = "32GB memory card for storage expansion.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Memory Card 32GB",
                            Price = 14.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            Description = "64GB memory card for more storage.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = true,
                            Name = "Memory Card 64GB",
                            Price = 24.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 9,
                            Description = "High-resolution camera for photography.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = false,
                            Name = "Camera",
                            Price = 499.99m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 9,
                            Description = "Tripod stand for cameras.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = false,
                            Name = "Tripod",
                            Price = 39.99m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 9,
                            Description = "Camera lens for versatile shooting.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = false,
                            Name = "Lens",
                            Price = 299.99m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 9,
                            Description = "Action camera for sports and adventures.",
                            ImagePath = "/images/products/placeholder.jpg",
                            IsPublished = false,
                            Name = "Action Camera",
                            Price = 199.99m,
                            StockQuantity = 6
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Discount", b =>
                {
                    b.HasOne("BackendApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("BackendApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendApi.Models.Product", b =>
                {
                    b.HasOne("BackendApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackendApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
